### ISSUE TITLE
QuickUnlock is not available for this database

### ISSUE THREAD

**Issue by rezelute** [KN4CK3R/KeePassQuickUnlock#11]
I have followed the instructions: Created a "QuickUnlock" entry in the database, entered the password, kept everything else blank, restarted keepass, it does not autofill the key file and when i select it, it just says "QuickUnlock is not available for this database". Am i missing something here?

**Comment by KN4CK3R** [comment]
QuickUnlock is only available if you lock your database. If you restart KeePass, the quickunlock key is not available because you haven't unlocked the database before. QuickUnlock just helps you to quickly unlock an already opened database (in the same KeePass session). If it would allow to unlock a new database it would be just a weaker master password.

**Comment by rezelute** [comment]
Ah, my bad, thank you for confirming this :)
