### ISSUE TITLE
QuickUnlock deletes KeyFilePath from Keepass.config.xml

### ISSUE THREAD

**Issue by schossel** [KN4CK3R/KeePassQuickUnlock#19]
There's an "Advanced" option in Keepass to remember key sources. The path to this sources seems to be saved in the config.xml at "KeyFilePath". When using QuickUnlock, it seems to me that QU changes this entry to something QU related in order to work. When Qu now gets invalidated after a given timeframe, the "KeyFilePath" is not being reversed to the entry before. So, after QU is invalidated, I have to chose the file path everytime again despite "remember key sources" is marked at the options tab.
If I just open Keepass, mark the "remember sources" option, close it and then just reopen it without letting QU interfere, it works like it should and the chosen keyfile path is readily selected at startup.
I used Keepass 2.35 for a long time and this worked! This problem seems to have appeared with the new Keepass 2.36. It's really annoying and perhaps you could have a look at it?

**Comment by KN4CK3R** [comment]
That shouldn't have worked with 2.35 too.
See #18 or #13. Both issues contain explanations why this sadly can't work.

**Comment by schossel** [comment]
I had it running since last year Nov-Dez. I only entered the key file path once and it worked like a charm. But now that you said it, I'm not sure if I did change something else to get this working. Bummer, can't remember.

**Comment by KN4CK3R** [comment]
I don't know if you are familar with the KeePass code but in the 2.36 AceDefaults.cs at line 255 is the SetKeySources method. The code checks if the masterkey contains a "KcpKeyFile" and if so sets the KeyFilePath. After a successfull quick unlock the masterkey contains only a "KcpCustomKey", so the KeyFilePath can't be set (The KeyProvider property gets set to the name of the custom key, "QuickUnlock" in this case.). It may work if name of the custom key returns the old key file path in the case no quick unlock is available. But then the plugin would need to store a list of file paths somewhere which isn't a good solution. The real solution I can think of would be a change in how KeePass requests the key of the plugin but I don't think this will change in the near future because there is no real need for it.

**Comment by schossel** [comment]
I looked at a few things and I'm pretty sure, if I enter <KeyFilePath>test.txt</KeyFilePath into the Keepass.config.enforced.xml, it seems to override the missing part in the Keepass.config.xml on restart. If QU now gets invalidated, couldn't you just read the KeyFilePath from there?

**Comment by KN4CK3R** [comment]
I looked through the code and I think it is not possible have a workaround for this. If you have enforced the KeyFilePath, doesn't it get added to the list so you can just select the path?

**Comment by schossel** [comment]
No. I would have to restart, so that the enforced config would put the KeyFilePath back into the normal config. That's why I asked you if it would be possible, at the time QU gets invalidated, to read the KeyFilePath from the enforced config and put it back into the normal config where it was before QU had to overwrite it.
